apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: {{ include "petclinic.name" . }}
spec:
  selector:
    app: {{ include "petclinic.name" . }}
  type: LoadBalancer
  ports:
    - nodePort: 32751
      port: 8080
      targetPort: 8080
